### ISSUE TITLE
error: unrecognized arguments: --field Ex

### ISSUE THREAD

**Issue by rajathkumarmp** [gprMax/gprMax#24]
While following the docs: http://docs.gprmax.com/en/latest/examples_simple_2D.html

This is the output of the command to plot merged B-Scan data.

```
Rajaths-MacBook-Pro:gprMax rajathkumarmp$ python3 -m tools.plot_Bscan cylinder_Bscan_2D_all.out --field Ex
usage: cd gprMax; python -m tools.plot_Bscan outputfile --field fieldcomponent
plot_Bscan.py: error: unrecognized arguments: --field Ex
```

**Comment by craig-warren** [comment]
Thanks for spotting this. 

I've corrected the `plot_Bscan` module and the docs should be updated shortly.

**Comment by rajathkumarmp** [comment]
@craig-warren 

There is still an error

```
Rajaths-MacBook-Pro:gprMax rajathkumarmp$ python3 -m tools.plot_Bscan cylinder_Bscan_2D_all.out Ex
Traceback (most recent call last):
  File "/Library/Frameworks/Python.framework/Versions/3.5/lib/python3.5/runpy.py", line 170, in _run_module_as_main
    "__main__", mod_spec)
  File "/Library/Frameworks/Python.framework/Versions/3.5/lib/python3.5/runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "/Users/rajathkumarmp/Desktop/gprMax/tools/plot_Bscan.py", line 37, in <module>
    availablecomponents = list(f[path].keys())
  File "h5py/_objects.pyx", line 54, in h5py._objects.with_phil.wrapper (/Users/travis/build/MacPython/h5py-wheels/h5py/h5py/_objects.c:2579)
  File "h5py/_objects.pyx", line 55, in h5py._objects.with_phil.wrapper (/Users/travis/build/MacPython/h5py-wheels/h5py/h5py/_objects.c:2538)
  File "/Library/Frameworks/Python.framework/Versions/3.5/lib/python3.5/site-packages/h5py/_hl/group.py", line 164, in __getitem__
    oid = h5o.open(self.id, self._e(name), lapl=self._lapl)
  File "h5py/_objects.pyx", line 54, in h5py._objects.with_phil.wrapper (/Users/travis/build/MacPython/h5py-wheels/h5py/h5py/_objects.c:2579)
  File "h5py/_objects.pyx", line 55, in h5py._objects.with_phil.wrapper (/Users/travis/build/MacPython/h5py-wheels/h5py/h5py/_objects.c:2538)
  File "h5py/h5o.pyx", line 190, in h5py.h5o.open (/Users/travis/build/MacPython/h5py-wheels/h5py/h5py/h5o.c:3551)
KeyError: 'Unable to open object (Component not found)'
```

The error is in `f[path]` it is an incorrect command.

**Comment by craig-warren** [comment]
I can't reproduce this error. Can you confirm that you have the 5022dd23 version of the `plot_Bscan` module and the sequence of steps you took:

`python -m gprMax user_models/cylinder_Bscan_2D.in -n 60`
`python -m tools.outputfiles_merge user_models/cylinder_Bscan_2D 60`
`python -m tools.plot_Bscan user_models/cylinder_Bscan_2D_all.out Ex`

**Comment by rajathkumarmp** [comment]
Working perfect now. Updated it to the latest version.
